name: Pruebas de Calculadora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verificar codigo
        run: python -m py_compile calculadora.py main.py

      - name: Ejecutar pruebas
        run: python -m unittest test_calculadora.py